name: Go

on:
  pull_request:
    branches:
      - "develop"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: backend

      - name: Get dependencies
        if: steps.changed.outputs.changed == 'true'
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      
      - name: Lint
        if: steps.changed.outputs.changed == 'true'
        uses: golangci/golangci-lint-action@v1.2.1

  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: backend

      - name: Get dependencies
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd backend
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Vet
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd backend
          go vet .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: backend

      - name: Get dependencies
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd backend
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd backend
          go test -v .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.0
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: marceloprado/has-changed-path@v1
      id: changed
      with:
        paths: backend

    - name: Get dependencies
      if: steps.changed.outputs.changed == 'true'
      run: |
        cd backend
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      if: steps.changed.outputs.changed == 'true'
      run: |
        cd backend
        go build -v .
