name: Node.js CI

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: app

      - name: CI
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd app
          npm ci

      - name: Test
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd app
          npm test

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: |
          cd app
          npm run build --if-present
